#workflow
name: My cool Workflow

#events
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
    myfirstjob:
              name: first job 
              runs-on: ubuntu-latest
              steps:
              - name: Step 1
                uses: actions/checkout@v3
              - name: Step 2
                run: | 
                  touch ${{ secrets.MY_SECRET }}.yaml
                  echo "Hello world" >> ${{ secrets.MY_SECRET }}.yaml
                  cat  ${{ secrets.MY_SECRET }}.yaml
                  pwd
    mysecondjob:
              needs: [myfirstjob]
              name: second job
              runs-on: macos-latest
              steps: 
              - name: Step 1
                run: date

    mythirdjob:
              name: third job
              runs-on: windows-latest
              steps: 
              - name: Step 1
                run: date
                
