#workflow
name: My cool Workflow

#events
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
    myfirstjob:
              name: first job 
              runs-on: ubuntu-latest
              steps:
              - name: Step 1
                uses: actions/checkout@v3
              - name: Step 2
                run: | 
                  touch newfile.yaml
                  echo "Hello world" >> newfile.yaml
                  cat newfile.yaml
                  pwd